cart/urls.py
from django.urls import path
from .views import AddCourseToCartView, CheckoutView, RevmoveCourseFromCartView, PaymentView

app_name = 'cart'
urlpatterns = [
    path('add/<str:content_type>/<int:course_id>/', AddCourseToCartView.as_view(), name='cart-add'),
    path('remove/<str:content_type>/<int:course_id>/', RevmoveCourseFromCartView.as_view(), name='cart-remove'),
    path('checkout/', CheckoutView.as_view(), name='cart-checkout'),
    path('payment/', PaymentView.as_view(), name='payment'),
]

myacademy/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('academy.urls')),
    path('', include('user.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('cart/', include('cart.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/models.py
from django.db import models
from user.models import User
from academy.models import Course
from django.utils.translation import gettext_lazy as _


class CartItem(models.Model):
    class ContentTypes(models.TextChoices):
        course = 'course', 'دوره ویدیویی'
        files = 'files', 'فایل'

    content_type = models.CharField(_("نوع دوره"), choices=ContentTypes.choices, default=ContentTypes.course, max_length=6)
    media_id = models.IntegerField(_("ایدی دوره"))
    price = models.IntegerField(_("قیمت"))

    class Meta:
        verbose_name = 'آیتم سبد خرید'
        verbose_name_plural = 'آیتم های سبد خرید'

    def get_object(self):
        content_type = {
            'course': Course,
        }
        return content_type[self.content_type].objects.get(id=self.media_id) if self.content_type in content_type.keys() else None

    def __str__(self):
        return f'{self.content_type} : {self.media_id}'


class Cart(models.Model):
    status_list = (('created', 'ساخته شده'), ('pending', 'در انتظار'), ('paid', 'پرداخت شده'))
    status = models.CharField(_("وضعیت"), choices = status_list, default='created', max_length=7)
    items = models.ManyToManyField(CartItem, verbose_name=_("دوره ها"))
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name=_("کاربر"))

    class Meta:
        verbose_name = 'سبد خرید'
        verbose_name_plural = 'سبد های خرید'

    def __str__(self):
        return self.user.__str__() + " : " + self.get_status_display()


class Order(models.Model):
    status_types = (('pending', 'در انتظار پرداخت'),
                    ('payed', 'پرداخت شده'),
                    ('failed', 'ناموفق'),)
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name=_('دانشجو'))
    total_price = models.IntegerField(_('قیمت کل'), blank=True, null=True)
    created_at = models.DateTimeField(_('زمان درخواست پرداخت'), auto_now_add=True)
    status = models.CharField(_('وضعت پرداخت'), choices=status_types, max_length=7, default='pending')
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE, verbose_name=_('سبد خرید'))
    payment_id = models.CharField(_("ای دی پرداخت"), max_length=100, blank=True)

    class Meta:
        verbose_name = 'سبد خرید'
        verbose_name_plural = 'سبد های خرید'
        ordering = ['pk']

    def __str__(self):
        return f'{self.id} - {self.user.__str__()} - {self.get_status_display()}'

cart/views.py
from django.conf import settings
from django.urls import reverse
from academy.models import Course
from .models import Cart, CartItem, Order
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import Http404
from django.shortcuts import get_object_or_404, redirect, render
from django.db.models import F, Sum
from django.db import transaction
from .utils import get_cart


class AddCourseToCartView(LoginRequiredMixin, View):
    http_method_names = ['post']

    def post(self, request, content_type, course_id, *args, **kwargs):
        content_types = {
            'course': Course,
        }
        if content_type not in content_types.keys():
            raise Http404()
        
        course = get_object_or_404(content_types[content_type], id = course_id)
        cart_item = CartItem.objects.create(content_type = content_type, media_id = course_id, price = course.get_final_price())
        cart, created = Cart.objects.get_or_create(user = request.user, status = 'created')
        if cart_item not in cart.items.all():
            cart.items.add(cart_item)

        return redirect(request.GET.get('next', course.get_absolute_url()))


class RevmoveCourseFromCartView(LoginRequiredMixin, View):
    http_method_names = ['post']

    def post(self, request, content_type, course_id, *args, **kwargs):
        content_types = {
            'course': Course,
        }
        if content_type not in content_types.keys():
            raise Http404()

        cart_item = get_object_or_404(CartItem, content_type = content_type, media_id = course_id)
        cart, created = Cart.objects.get_or_create(user = request.user, status = 'created')
        if cart_item in cart.items.all():
            cart.items.remove(cart_item)
            cart_item.delete()

        return redirect(request.GET.get('next', cart_item.get_object().get_absolute_url()))


class CheckoutView(LoginRequiredMixin, View):
    template_name = 'cart/checkout.html'

    def dispatch(self, request, *args, **kwargs):
        cart, self.total_price, cart_courses = get_cart(request.user)

        self.context = {
            'cart_courses': cart_courses,
            'total_price': self.total_price,
        }
        return super().dispatch(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name, self.context)

    def post(self, request, *args, **kwargs):
        

        return render(request, self.template_name, self.context)


class PaymentView(LoginRequiredMixin, View):
    def post(self, request, *args, **kwargs):
        # order, created = Order.objects.get_or_create(user = request.user, status = 'created')
        cart, total_price, cart_courses = get_cart(request.user)

        try:
            with transaction.atomic():
                order, created = Order.objects.get_or_create(
                    user = request.user,
                    total_price = total_price,
                    status = 'pending',
                    cart = cart,
                    # payment_id = '' # payment id
                    )
                Cart.objects.filter(user = request.user, status = 'created').update(status = 'pending')
                # user.balance -= total_price
                # user.save()

                cart.status = 'pending'
                cart.save()

            user = request.user
            if settings.BYPASS_SHOPPING or user.balance >= total_price:
                with transaction.atomic():
                    order.status = 'paid'
                    order.save()

                    if not settings.BYPASS_SHOPPING:
                        user.balance -= total_price
                        user.save()
                # TODO: redirect to bought products url
                return redirect('academy:home')
            else:
                return redirect('academy:home') # redirect to paymend url
        except Exception as ex:
            print('ERROR: In Checkout view in POST method in save order.')
            print(ex)
            return redirect('academy:home') # redirect to paymend url

templates/cart/checkout.html
{% extends 'academy/base.html' %}
{% load static %}
{% block title %}تایید سبد خرید | آکادمی من{% endblock %}
{% block content %}
    <main>
        <section class="tp-cart-area pt-120 pb-120">
            <div class="container">
                <div class="row">
                    <div class="col-xl-9 col-lg-8">
                        <div class="tp-cart-list mb-25 mr-30">
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th class="tp-cart-header-product" colspan="2">محصول</th>
                                        <th class="tp-cart-header-price">قیمت</th>
                                        <th class="tp-cart-header-quantity">مقدار</th>
                                        <th></th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for product in cart_courses %}
                                    <tr>
                                        <td class="tp-cart-img">
                                            <a href="{{ product.get_object.get_absolute_url }}">
                                                <img alt="" src="{{ product.get_object.thumbnail.url }}">
                                            </a>
                                        </td>
                                        <td class="tp-cart-title"><a href="shop-details.html">{{ product.get_object.name }}</a></td>
                                        <td class="tp-cart-price"><span>{{ product.get_object.price_final_price|default:product.get_object.price }} تومان</span></td>
                                        <td class="tp-cart-action">
                                            <a onclick="sendFormToURL('{{ product.get_object.get_remove_from_cart_url }}?next={{ request.get_full_path }}')" style="background-color: orangered; color: black;" class="tp-cart-action-btn border border-2 rounded-2 p-1">
                                                <svg fill="none" height="10" viewbox="0 0 10 10" width="10" xmlns="http://www.w3.org/2000/svg">
                                                    <path clip-rule="evenodd"
                                                        d="M9.53033 1.53033C9.82322 1.23744 9.82322 0.762563 9.53033 0.46967C9.23744 0.176777 8.76256 0.176777 8.46967 0.46967L5 3.93934L1.53033 0.46967C1.23744 0.176777 0.762563 0.176777 0.46967 0.46967C0.176777 0.762563 0.176777 1.23744 0.46967 1.53033L3.93934 5L0.46967 8.46967C0.176777 8.76256 0.176777 9.23744 0.46967 9.53033C0.762563 9.82322 1.23744 9.82322 1.53033 9.53033L5 6.06066L8.46967 9.53033C8.76256 9.82322 9.23744 9.82322 9.53033 9.53033C9.82322 9.23744 9.82322 8.76256 9.53033 8.46967L6.06066 5L9.53033 1.53033Z"
                                                        fill="currentColor" fill-rule="evenodd"></path>
                                                </svg>
                                                <span>حذف</span>
                                            </a>
                                        </td>
                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                        <div class="tp-cart-bottom">
                            <div class="row align-items-end">
                                <div class="col-xl-6 col-md-8">
                                    <div class="tp-cart-coupon">
                                        <form action="cart.html#">
                                            <div class="tp-cart-coupon-input-box"><label>کد کوپن:</label>
                                                <div class="tp-cart-coupon-input d-flex align-items-center">
                                                    <input placeholder="کد کوپن را وارد کنید" type="text">
                                                    <button type="submit">درخواست</button>
                                                </div>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                                <div class="col-xl-6 col-md-4">
                                    <form method="post" class="tp-cart-update text-md-end">
                                        {% csrf_token %}
                                        <button type="submit" class="tp-cart-update-btn" type="button">به روز رسانی سبد خرید</button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-xl-3 col-lg-4 col-md-6">
                        <div class="tp-cart-checkout-wrapper">
                            <div class="tp-cart-checkout-total d-flex align-items-center justify-content-between">
                                <span>مجموع</span>
                                <span>{{ total_price }} تومان</span>
                            </div>
                            <div class="tp-cart-checkout-proceed">
                                <a class="tp-cart-checkout-btn w-100" onclick="sendFormToURL('{% url 'cart:payment' %}')">تسویه حساب</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </main>
{% endblock %}