academy/urls.py
from django.urls import path
from .views import (Home, CourseFilterView, CourseCategoryView, CourseDetailsView, BookmarkView)


app_name = 'academy'
urlpatterns = [
    path('courses', CourseFilterView.as_view(), name='courseslist'),
    path('category/<slug:category_slug>', CourseCategoryView.as_view(), name='category'),
    path('bookmark/<str:content_type>/<int:course_id>/', BookmarkView.as_view(), name='bookmarker'),
    path('courses/<int:course_id>', CourseDetailsView.as_view(), name='course-details'),
    path('', Home.as_view(), name = 'home'),
]

cart/urls.py
from django.urls import path
from .views import AddCourseToCartView, CheckoutView, RevmoveCourseFromCartView, PaymentView

app_name = 'cart'
urlpatterns = [
    path('add/<str:content_type>/<int:course_id>/', AddCourseToCartView.as_view(), name='cart-add'),
    path('remove/<str:content_type>/<int:course_id>/', RevmoveCourseFromCartView.as_view(), name='cart-remove'),
    path('checkout/', CheckoutView.as_view(), name='cart-checkout'),
    path('payment/', PaymentView.as_view(), name='payment'),
]

myacademy/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('academy.urls')),
    path('', include('user.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('cart/', include('cart.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

academy/models.py
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from user.models import User
from .managers import CommentManager
from django.db.models import Count, Sum


class Course(models.Model):
    name = models.CharField(_("نام"), max_length=300)
    category = models.ManyToManyField('Category', blank=True, related_name='courses', verbose_name=_('دسته بندی'))
    teacher = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name=_('مدرس'))
    description = models.TextField(_('درباره دوره'))
    seasions = models.ManyToManyField('Seasion', blank=True, verbose_name=_('فصل ها'))
    price= models.IntegerField(_('قیمت'), default=0)
    price_with_discount = models.IntegerField(_('قیمت با تخفیف'), blank=True, null=True)
    tax = models.DecimalField(_('مالیات'), max_digits=4, decimal_places=2, default=0.0, help_text='درصد مالیات')
    related_course = models.ManyToManyField('self', blank=True, verbose_name=_('دوره های مرتبط'))
    thumbnail = models.ImageField(_('عکس'), upload_to='courses/images/')
    time = models.TimeField(_('زمان'))
    skils_type = (('j', 'مبتدی'), ('m', 'متوسط'), ('s', 'پیشرفته'))
    difficulty_level = models.CharField(_('سظح مهارت'), default='j', choices=skils_type, max_length=1)
    is_certificate = models.BooleanField(_('دارای مدرک'), default=True)
    trailer = models.FileField(_('ویدیو معرفی'), blank=True, upload_to='courses/trailer/')
    is_askable = models.BooleanField(_('اجازه پرسش و پاسخ'), default=True)
    is_active = models.BooleanField(_('فعال'), help_text='وضعیت نمایش به دانشجو', default=False)
    updated_at = models.DateTimeField(_('اپدیت شده در'), auto_now=True)
    created_at = models.DateTimeField(_('زمان ساخت'), auto_now_add=True)


    class Meta:
        verbose_name = 'دوره'
        verbose_name_plural = 'دوره ها'
        ordering = ['is_active', 'created_at']

    def lessons_count(self):
        return self.seasions.annotate(lessons_count = Count('lessons')).aggregate(count = Sum('lessons_count'))['count'] or 0
    
    def get_final_price(self):
        """
        ###Final Price
        return price with discount and tax
        """
        return int(self.price_with_discount + (self.price // 100 * self.tax) if self.price_with_discount else self.price + (self.price // 100 * self.tax))

    def get_absolute_url(self):
        return reverse('academy:course-details', args=[self.pk])

    def get_purch_url(self):
        return reverse('cart:cart-add', args=['course', self.pk])

    def get_remove_from_cart_url(self):
        return reverse('cart:cart-remove', args=['course', self.pk])

    def __str__(self):
        return self.name


class Comment(models.Model):
    comment_class = (('course', 'دوره'),)
    media_id = models.IntegerField(_('ایدی مدیا'))
    media_type = models.CharField(_('نوع'), default='course', max_length=10, choices=comment_class)
    message = models.TextField(_('پیام'))
    parent  = models.ForeignKey('self', on_delete=models.CASCADE, blank=True, null=True, verbose_name=_('کامنت والد'))
    created_at = models.DateTimeField(_('زمان ارسال'), auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name=_('کاربر'))
    active = models.BooleanField(_('وضعیت'), default=False)
    objects = CommentManager()

    def get_media(self, obj):
        objects = {
            'course': Course,
        }
        return objects[obj].objects.get(id = self.media_id)
    
    class Meta:
        verbose_name = 'کامنت'
        verbose_name_plural = 'کامنت ها'
        ordering = ['active', 'created_at']

    def __str__(self):
        return f'{self.user.__str__()}:{self.pk}'


class Category(models.Model):
    title = models.CharField(_('موضوع'), max_length=250)
    slug = models.SlugField(_('سلاگ'), max_length=300, unique=True)

    class Meta:
        verbose_name = 'دسته بندی'
        verbose_name_plural = 'دسته بندی ها'
        ordering = ['title']

    def get_active_courses_count(self):
        return self.courses.filter(is_active = True).count()

    def get_absolute_url(self):
        return reverse('academy:category', args=[self.slug])

    def __str__(self):
        return self.title


class Team(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name=_('کاربر'))
    social_telegram = models.URLField(_('ادرس تلگرام'), blank=True)
    social_rubika = models.URLField(_('ادرس روبیکا'), blank=True)
    social_instagram = models.URLField(_('ادرس اینستاگرام'), blank=True)
    social_github = models.URLField(_('ادرس گیتهاب'), blank=True)
    image = models.ImageField(_('عکس کاربر'), blank=True, upload_to='users/team/profiles/', help_text='260px * 350px none background')
    position = models.TextField(_('سِمَت'), max_length=150)

    class Meta:
        verbose_name = 'عضو تیم'
        verbose_name_plural = 'اعضای تیم'
        ordering = ['id']

    def __str__(self):
        return self.user.__str__()


class Lesson(models.Model):
    title = models.CharField(_('نام درس'), max_length=200)
    description = models.TextField(_('درباره این قسمت'))
    file = models.FileField(_('فلیم'), upload_to='courses/lessons/files/')
    attached = models.FileField(_('پیوست'), blank=True)
    time = models.TimeField(_('زمان'), blank=True, null=True)
    teacher = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name=_('مدرس'))
    is_free = models.BooleanField(_('رایگان'), default=False)

    class Meta:
        verbose_name = 'درس'
        verbose_name_plural = 'درس ها'
        ordering = ['title']

    def __str__(self):
        return self.title


class Seasion(models.Model):
    title = models.CharField(_('موضوع'), max_length=250)
    lessons = models.ManyToManyField(Lesson, blank=True, verbose_name=_('درس ها'))

    class Meta:
        verbose_name = 'فصل'
        verbose_name_plural = 'فصل ها'
        ordering = ['id']

    def __str__(self):
        return self.title


class MainPageCategoryAdd(models.Model):
    title = models.CharField(_('نام تبلیغاتی دسته بندی '), max_length=150)
    image = models.ImageField(_('عکس تبلیغاتی دسته بندی'), upload_to='categorys/images/')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name=_('دسته بندی'))

    class Meta:
        verbose_name = 'دسته بندی تبلیغاتی صفحه خانه'
        verbose_name_plural = 'دسته بندی های تبلیغاتی صفحه خانه'
        ordering = ['id']

    def __str__(self):
        return self.title


class MainPageCourseAdd(models.Model):
    title = models.CharField(_('نام تب محصولات '), max_length=150)
    courses = models.ManyToManyField(Course, verbose_name=_('دسته بندی'))

    class Meta:
        verbose_name = 'محصول تبلیغاتی صفحه خانه'
        verbose_name_plural = 'محصولات تبلیغاتی صفحه خانه'
        ordering = ['id']

    def __str__(self):
        return self.title


class Bookmark(models.Model):
    content_types = (('course', 'دوره ویدیویی'), ('file', 'فایل'))
    content_type = models.CharField(_("نوع محتوا"), max_length=6, choices=content_types)
    media_id = models.IntegerField(_("ایدی محصول"))
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name=_("کاربر"))

    class Meta:
        verbose_name = "محصولات / پست های ذخیره شده"
        verbose_name_plural = "محصول / پست ذخیره شده"
        ordering = ['id']

    def get_object(self):
        content_types = {
            'course': Course,
        }
        return content_types[self.content_type].objects.get(id=self.media_id)

    def __str__(self):
        return f"{self.content_type} : {self.media_id}"

cart/models.py
from django.db import models
from user.models import User
from academy.models import Course
from django.utils.translation import gettext_lazy as _


class CartItem(models.Model):
    class ContentTypes(models.TextChoices):
        course = 'course', 'دوره ویدیویی'
        files = 'files', 'فایل'

    content_type = models.CharField(_("نوع دوره"), choices=ContentTypes.choices, default=ContentTypes.course, max_length=6)
    media_id = models.IntegerField(_("ایدی دوره"))
    price = models.IntegerField(_("قیمت"))

    class Meta:
        verbose_name = 'آیتم سبد خرید'
        verbose_name_plural = 'آیتم های سبد خرید'

    def get_object(self):
        content_type = {
            'course': Course,
        }
        return content_type[self.content_type].objects.get(id=self.media_id) if self.content_type in content_type.keys() else None

    def __str__(self):
        return f'{self.content_type} : {self.media_id}'


class Cart(models.Model):
    status_list = (('created', 'ساخته شده'), ('pending', 'در انتظار'), ('paid', 'پرداخت شده'))
    status = models.CharField(_("وضعیت"), choices = status_list, default='created', max_length=7)
    items = models.ManyToManyField(CartItem, verbose_name=_("دوره ها"))
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name=_("کاربر"))

    class Meta:
        verbose_name = 'سبد خرید'
        verbose_name_plural = 'سبد های خرید'

    def __str__(self):
        return self.user.__str__() + " : " + self.get_status_display()


class Order(models.Model):
    status_types = (('pending', 'در انتظار پرداخت'),
                    ('payed', 'پرداخت شده'),
                    ('failed', 'ناموفق'),)
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name=_('دانشجو'))
    total_price = models.IntegerField(_('قیمت کل'), blank=True, null=True)
    created_at = models.DateTimeField(_('زمان درخواست پرداخت'), auto_now_add=True)
    status = models.CharField(_('وضعت پرداخت'), choices=status_types, max_length=7, default='pending')
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE, verbose_name=_('سبد خرید'))
    payment_id = models.CharField(_("ای دی پرداخت"), max_length=100, blank=True)

    class Meta:
        verbose_name = 'سبد خرید'
        verbose_name_plural = 'سبد های خرید'
        ordering = ['pk']

    def __str__(self):
        return f'{self.id} - {self.user.__str__()} - {self.get_status_display()}'

cart/views.py
from django.conf import settings
from django.urls import reverse
from academy.models import Course
from .models import Cart, CartItem, Order
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import Http404
from django.shortcuts import get_object_or_404, redirect, render
from django.db.models import F, Sum
from django.db import transaction
from .utils import get_cart


class AddCourseToCartView(LoginRequiredMixin, View):
    http_method_names = ['post']

    def post(self, request, content_type, course_id, *args, **kwargs):
        content_types = {
            'course': Course,
        }
        if content_type not in content_types.keys():
            raise Http404()
        
        course = get_object_or_404(content_types[content_type], id = course_id)
        cart_item = CartItem.objects.create(content_type = content_type, media_id = course_id, price = course.get_final_price())
        cart, created = Cart.objects.get_or_create(user = request.user, status = 'created')
        if cart_item not in cart.items.all():
            cart.items.add(cart_item)

        return redirect(request.GET.get('next', course.get_absolute_url()))


class RevmoveCourseFromCartView(LoginRequiredMixin, View):
    http_method_names = ['post']

    def post(self, request, content_type, course_id, *args, **kwargs):
        content_types = {
            'course': Course,
        }
        if content_type not in content_types.keys():
            raise Http404()

        cart_item = get_object_or_404(CartItem, content_type = content_type, media_id = course_id)
        cart, created = Cart.objects.get_or_create(user = request.user, status = 'created')
        if cart_item in cart.items.all():
            cart.items.remove(cart_item)
            cart_item.delete()

        return redirect(request.GET.get('next', cart_item.get_object().get_absolute_url()))


class CheckoutView(LoginRequiredMixin, View):
    template_name = 'cart/checkout.html'

    def dispatch(self, request, *args, **kwargs):
        cart, self.total_price, cart_courses = get_cart(request.user)

        self.context = {
            'cart_courses': cart_courses,
            'total_price': self.total_price,
        }
        return super().dispatch(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name, self.context)

    def post(self, request, *args, **kwargs):
        

        return render(request, self.template_name, self.context)


class PaymentView(LoginRequiredMixin, View):
    def post(self, request, *args, **kwargs):
        # order, created = Order.objects.get_or_create(user = request.user, status = 'created')
        cart, total_price, cart_courses = get_cart(request.user)

        try:
            with transaction.atomic():
                order, created = Order.objects.get_or_create(
                    user = request.user,
                    total_price = total_price,
                    status = 'pending',
                    cart = cart,
                    # payment_id = '' # payment id
                    )
                Cart.objects.filter(user = request.user, status = 'created').update(status = 'pending')
                # user.balance -= total_price
                # user.save()

                cart.status = 'pending'
                cart.save()

            user = request.user
            if settings.BYPASS_SHOPPING or user.balance >= total_price:
                with transaction.atomic():
                    order.status = 'paid'
                    order.save()

                    if not settings.BYPASS_SHOPPING:
                        user.balance -= total_price
                        user.save()
                # TODO: redirect to bought products url
                return redirect('academy:home')
            else:
                return redirect('academy:home') # redirect to paymend url
        except Exception as ex:
            print('ERROR: In Checkout view in POST method in save order.')
            print(ex)
            return redirect('academy:home') # redirect to paymend url

templates/components/cart.html
{% load static %}
<div class="cartmini__area">
    <div class="cartmini__wrapper p-relative d-flex justify-content-between flex-column">
        <div class="cartmini__close">
            <button class="cartmini__close-btn cartmini-close-btn" type="button">
                <i class="fal fa-times"></i>
            </button>
        </div>
        <div class="cartmini__top-wrapper">
            <div class="cartmini__top p-relative">
                <div class="cartmini__top-title">
                    <h4>سبد خرید</h4>
                </div>
            </div>
            {% if cart_courses|length > 0 %}
            <div class="cartmini__widget">
                {% for course in cart_courses %}
                <div class="cartmini__widget-item">
                    <div class="cartmini__thumb">
                        <a href="{{ course..get_object.get_absolute_url }}">
                            <img alt="" src="{{ course.get_object.thumbnail.url }}">
                        </a>
                    </div>
                    <div class="cartmini__content">
                        <h5 class="cartmini__title home-2"><a href="{{ course.get_object.get_absolute_url }}">{{ course.name }}</a></h5>
                        <div class="cartmini__price-wrapper">
                            <span class="cartmini__price home-2">{{ course.get_object.price }} تومان</span>
                        </div>
                    </div>
                    <a class="cartmini__del home-2" onclick="sendFormToURL('{{ course.get_object.get_remove_from_cart_url }}?next={{request.get_full_path}}')"><i class="fa-regular fa-xmark"></i></a>
                </div>
                {% endfor %}
            </div>
            {% else %}
            <div class="cartmini__empty text-center">
                <img alt="" src="{% static 'img/shop/empty-cart.png' %}">
                <p>سبد خرید شما خالی است</p>
                <a class="tp-btn" href="#">برو به فروشگاه</a>
            </div>
            {% endif %}
        </div>
        <div class="cartmini__checkout">
            <div class="cartmini__checkout-title mb-30">
                <h4>قیمت کل:</h4>
                <span>
                    {% if total_price > 0 %}{{ total_price }} تومان{% else %}رایگان{% endif %}</span>
            </div>
            <div class="cartmini__checkout-btn home-2">
                <a class="tp-btn mb-10 w-100" href="{% url 'cart:cart-checkout' %}">مشاهده سبد خرید</a>
                <a class="tp-btn tp-btn-border w-100" href="{% url 'cart:cart-checkout' %}">نهایی سازی خرید</a>
            </div>
        </div>
    </div>
</div>
<script>
    function sendFormToURL(url) {
        let csrf = document.cookie.split('; ').find(row => row.startsWith('csrftoken'))?.split('=')[1];
        const form = document.createElement("form");
        form.method = "POST";
        form.action = url;

        const input = document.createElement("input");
        input.type = "hidden";
        input.name = "csrfmiddlewaretoken";
        input.value = csrf;
        form.append(input);

        document.body.appendChild(form);
        form.submit();
    }
</script>

templates/components/course.html
<div class="col-lg-4 col-md-6">
    <div class="tp-course-item card p-relative fix mb-30">
        <div class="tp-course-teacher mb-15">
            <span>
                <img alt="" src="{{ course.teacher.get_photo }}">
                {{ course.teacher.get_full_name|default:course.teacher.username }}
            </span>
        </div>
        <div class="tp-course-thumb">
            <a href="{{ course.get_absolute_url }}">
                <img alt="" class="course-pink" src="{{ course.thumbnail.url }}">
            </a>
        </div>
        <div class="tp-course-content">
            <div class="tp-course-tag mb-10">
                {% for category in course.category.all %}
                <a href="{% url 'academy:category' category.slug %}">{{ category.title }}</a>
                {% endfor %}
            </div>
            <div class="tp-course-meta">
                <span>
                    <span>
                        <svg fill="none" height="14" viewbox="0 0 15 14" width="15" xmlns="http://www.w3.org/2000/svg">
                            <path
                                d="M13.9228 10.0426V2.29411C13.9228 1.51825 13.2949 0.953997 12.5252 1.01445H12.4847C11.1276 1.12529 9.07163 1.82055 7.91706 2.53596L7.80567 2.6065C7.62337 2.71733 7.30935 2.71733 7.11692 2.6065L6.9549 2.50573C5.81046 1.79033 3.75452 1.1152 2.3974 1.00437C1.62768 0.943911 0.999756 1.51827 0.999756 2.28405V10.0426C0.999756 10.6573 1.50613 11.2417 2.12393 11.3122L2.30622 11.3425C3.70386 11.5238 5.87126 12.2392 7.10685 12.9143L7.1372 12.9244C7.30937 13.0252 7.59293 13.0252 7.75498 12.9244C8.99057 12.2393 11.1681 11.5339 12.5758 11.3425L12.7885 11.3122C13.4164 11.2417 13.9228 10.6674 13.9228 10.0426Z"
                                stroke="#94928E" stroke-linecap="round"
                                stroke-linejoin="round" stroke-width="1.2"></path>
                            <path d="M7.46118 2.81787V12.4506" stroke="#94928E"
                                stroke-linecap="round" stroke-linejoin="round"
                                stroke-width="1.2"></path>
                        </svg>
                    </span>
                    {{ course.lessons_count }} درس
                </span>
                <span>
                    <span>
                        <svg fill="none" height="15" viewbox="0 0 13 15" width="13" xmlns="http://www.w3.org/2000/svg">
                            <path
                                d="M6.57134 7.5C8.36239 7.5 9.81432 6.04493 9.81432 4.25C9.81432 2.45507 8.36239 1 6.57134 1C4.7803 1 3.32837 2.45507 3.32837 4.25C3.32837 6.04493 4.7803 7.5 6.57134 7.5Z"
                                stroke="#94928E" stroke-linecap="round"
                                stroke-linejoin="round" stroke-width="1.2"></path>
                            <path
                                d="M12.1426 14C12.1426 11.4845 9.64553 9.44995 6.57119 9.44995C3.49684 9.44995 0.999756 11.4845 0.999756 14"
                                stroke="#94928E" stroke-linecap="round"
                                stroke-linejoin="round" stroke-width="1.2"></path>
                        </svg>
                    </span>
                    45 دانش آموز
                </span>
            </div>
            <h4 class="tp-course-title"><a href="{{ course.get_absolute_url }}">{{ course.name }}</a></h4>
            <div class="tp-course-rating d-flex align-items-end justify-content-between">
                <div class="tp-course-rating-star">
                    <p>5.0<span>/5</span></p>
                    <div class="tp-course-rating-icon">
                        <i class="fa-solid fa-star"></i>
                        <i class="fa-solid fa-star"></i>
                        <i class="fa-solid fa-star"></i>
                        <i class="fa-solid fa-star"></i>
                        <i class="fa-solid fa-star"></i>
                    </div>
                </div>
                <div class="tp-course-pricing">
                    {% if course.price == 0 %}
                    <span>رایگان !</span>
                    {% elif course.price_with_discount != 0 %}
                    <del>{{ course.price }} تومان</del>
                    <span>{{ course.price_with_discount }} تومان</span>
                    {% else %}
                    <span>{{ couse.price }} تومان</span>
                    {% endif %}
                </div>
            </div>
        </div>
        <div class="tp-course-btn">
            <div class="row justify-content-between">
                <a class="col-7" href="{{ course.get_absolute_url }}">جزیات دوره</a>
                {% if course.id in all_bookmarks %} 
                <a class="col-4" onclick="sendFormToURL('{% url 'academy:bookmarker' 'course' course.id %}?next={{ request.get_full_path}}')" style="background-color: #5169F1;">ذخیره شده</a>
                {% else %}
                <a class="col-4" style="background-color: #FF5E74;" onclick="sendFormToURL('{% url 'academy:bookmarker' 'course' course.id %}?next={{ request.get_full_path}}')">ذخیره نشده</a>
                {% endif %}
            </div>
        </div>
    </div>
</div>

templates/components/pagination.html
<nav aria-label="Page navigation example">
    <ul class="pagination pagination-lg justify-content-center">
      <li class="page-item {% if not object.has_previous %} disabled {% endif %}">
        <a class="page-link" href="?page=1">اول</a>
      </li>
      {% if object.has_previous and object.previous_page_number > 1 %}
      <li class="page-item"><a class="page-link" href="?page={{ object.previous_page_number }}">{{ object.previous_page_number }}</a></li>
      {% endif %}

      <li class="page-item active"><a class="page-link" href="?page={{ object.number }}">{{ object.number }}</a></li>

      {% if object.has_next  %}
      <li class="page-item"><a class="page-link" href="?page={{ object.next_page_number }}">{{ object.next_page_number }}</a></li>
      {% endif %}

      <li class="page-item {% if not object.has_next %} disabled {% endif %}">
        <a class="page-link" href="?page={{ object.paginator.num_pages }}">آخر</a>
      </li>
    </ul>
</nav>