academy/urls.py
from django.urls import path
from .views import (Home, CourseFilterView, CourseCategoryView, CourseDetailsView, BookmarkView)


app_name = 'academy'
urlpatterns = [
    path('courses', CourseFilterView.as_view(), name='courseslist'),
    path('category/<slug:category_slug>', CourseCategoryView.as_view(), name='category'),
    path('bookmark/<str:content_type>/<int:course_id>/', BookmarkView.as_view(), name='bookmarker'),
    path('courses/<int:course_id>', CourseDetailsView.as_view(), name='course-details'),
    path('', Home.as_view(), name = 'home'),
]

cart/urls.py
from django.urls import path
from .views import AddCourseToCartView, CheckoutView, RevmoveCourseFromCartView, PaymentView

app_name = 'cart'
urlpatterns = [
    path('add/<str:content_type>/<int:course_id>/', AddCourseToCartView.as_view(), name='cart-add'),
    path('remove/<str:content_type>/<int:course_id>/', RevmoveCourseFromCartView.as_view(), name='cart-remove'),
    path('checkout/', CheckoutView.as_view(), name='cart-checkout'),
    path('payment/', PaymentView.as_view(), name='payment'),
]

dashboard/urls.py
from django.urls import path
from .views import (ProfileView, ChangePasswordView, CourseAddView, CourseUpdateView, CourseDeleteView, MyCourseView, MyCourseNotPublishedView,
                    MyBookmarkListView)

app_name = 'dashboard'
urlpatterns = [
    path('profile/', ProfileView.as_view(), name = 'profile'),
    path('change-password/', ChangePasswordView.as_view(), name = 'change-password'),
    path('course/add/', CourseAddView.as_view(), name='course-add'),
    path('course/<int:pk>/update/', CourseUpdateView.as_view(), name='course-update'),
    path('course/<int:pk>/delete/', CourseDeleteView.as_view(), name='course-delete'),
    path('my-course/', MyCourseView.as_view(), name='my-courses'),
    path('my-course/pending/', MyCourseNotPublishedView.as_view(), name='my-courses-not-published'),
    path('my-bookmarks/', MyBookmarkListView.as_view(), name='my-bookmark-list'),

]

myacademy/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('academy.urls')),
    path('', include('user.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('cart/', include('cart.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/models.py
from django.db import models

# Create your models here.

dashboard/forms.py
from django import forms
from academy.models import Course, Seasion
from user.models import Profile, User


class UserProfileForm(forms.ModelForm):
    first_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'input'}), required=False, label='نام')
    last_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'input'}), required=False, label='نام خانوادگی')
    username = forms.CharField(validators=[], widget=forms.TextInput(attrs={'class': 'input'}), required=False, label='نام کاربری')

    class Meta:
        model = Profile
        fields = ['aboute', 'picture']
        widgets = {
            'aboute': forms.Textarea(attrs={'class': 'input', 'style': 'height: auto;', 'rows': 5}),
            'picture': forms.FileInput(attrs={'class': 'input'})
        }

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        super().__init__(*args, **kwargs)
        
        if self.user:
            self.fields['first_name'].initial = self.user.first_name
            self.fields['last_name'].initial = self.user.last_name
            self.fields['username'].initial = self.user.username

    def save(self, commit = True):
        profile = super().save(commit=False)
        user = profile.user
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.username = self.cleaned_data['username']
        if commit:
            user.save()
            profile.save()
        return user

    def clean_username(self):
        username = self.cleaned_data['username']
        if self.user.username != username and User.objects.filter(username=username).exists():
            raise forms.ValidationError('نام کاربری تکراری است.')
        return username


class PasswordChangeForm(forms.Form):
    last_password = forms.CharField(max_length=100, label='پسورد قبلی', widget=forms.PasswordInput)
    new_password1 = forms.CharField(
        max_length=100, label='پسورد جدید',
        widget=forms.PasswordInput,
        help_text= 'پسورد باید ترکیبی از متن و عدد و بیشتر از ۷ کاراکتر باشد.'
        )
    new_password2 = forms.CharField(max_length=100, label='تکرار پسورد', widget=forms.PasswordInput)

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        super().__init__(*args, **kwargs)

    def clean(self):
        cleaned_data = super().clean()
        new_password1 = cleaned_data['new_password1']
        new_password2 = cleaned_data['new_password2']
        last_password = cleaned_data['last_password']
        if new_password1 != new_password2:
            raise forms.ValidationError('پسورد جدبد و تکرار ان باید با هم مشابه باشند.')
        elif not new_password1 or not last_password or len(new_password1) < 7:
            raise forms.ValidationError('پسورد باید ترکیبی از متن و عدد و بیشتر از ۷ کاراکتر باشد.')
        elif not self.user.check_password(self.cleaned_data['last_password']):
            raise forms.ValidationError('پسورد قبلی اشتباه است.')
        return cleaned_data

    def save(self, commit = True):
        self.user.set_password(self.cleaned_data['new_password1'])
        self.user.save()
        return self.user

dashboard/views.py
from django.views.generic import UpdateView, FormView, CreateView, DeleteView, ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy, reverse
from django.shortcuts import redirect
from django.contrib import messages
from .forms import UserProfileForm, PasswordChangeForm
from academy.forms import CourseForm, SeasionFormSet
from user.models import Profile
from academy.models import Bookmark, Course, Seasion
from cart.models import Cart
from cart.utils import get_cart
from django.db.models import Count


class ProfileView(LoginRequiredMixin, UpdateView):
    template_name = 'dashboard/profile.html'
    model = Profile
    form_class = UserProfileForm
    success_url = reverse_lazy('user:profile')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['current_page'] = 'profile'

        cart, total_price, cart_courses = get_cart(self.request.user)
        context['cart_courses'] = cart_courses
        context['total_price'] = total_price
        return context

    def get_object(self):
        return self.request.user.profile

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def form_valid(self, form):
        form.save()
        messages.success(self.request, 'پروفایل با موفقیت آپدیت شد.')
        return self.render_to_response(self.get_context_data(form=form))


class ChangePasswordView(LoginRequiredMixin, FormView):
    template_name = 'dashboard/change-password.html'
    form_class = PasswordChangeForm
    success_url = reverse_lazy('user:login')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['current_page'] = 'profile'

        cart, total_price, cart_courses = get_cart(self.request.user)
        context['cart_courses'] = cart_courses
        context['total_price'] = total_price
        return context

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def form_valid(self, form):
        form.save()
        return redirect('user:login')


class CourseAddView(CreateView):
    model = Course
    form_class = CourseForm
    success_url = '/'
    template_name = 'dashboard/course.html'

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return redirect(reverse('user:login') + '?next=' + reverse('dashboard:course-add'))
        elif not request.user.is_mentor:
            if not request.user.is_superuser:
                return redirect('dashboard:profile')
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['current_page'] = 'course-add'
        context['seasion_formset'] = SeasionFormSet(self.request.POST) if self.request.method == 'POST' else SeasionFormSet()
        
        cart, total_price, cart_courses = get_cart(self.request.user)
        context['cart_courses'] = cart_courses
        context['total_price'] = total_price
        return context

    def form_valid(self, form):
        seasion_formset = SeasionFormSet(self.request.POST)
        if seasion_formset.is_valid():
            self.object = form.save(teacher = self.request.user)

            seasion_instances = []
            for seasion_form in seasion_formset:
                if seasion_form.cleaned_data.get('title'):
                    seasion = seasion_form.save(commit=False)
                    seasion_instances.append(seasion)
            
            seasion_instances = Seasion.objects.bulk_create(seasion_instances)
            self.object.seasions.set(seasion_instances)

            return redirect(reverse('dashboard:course-update', args=[self.object.pk]))
        else:
            return self.form_invalid(form)


class CourseUpdateView(UpdateView):
    model = Course
    form_class = CourseForm
    template_name = 'dashboard/course.html'

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return redirect(reverse('user:login') + '?next=' + reverse('dashboard:course-update', args=[self.get_object().pk]))
        elif not request.user.is_mentor:
            if not request.user.is_superuser:
                return redirect('dashboard:profile')
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['current_page'] = 'course-update'

        cart, total_price, cart_courses = get_cart(self.request.user)
        context['cart_courses'] = cart_courses
        context['total_price'] = total_price
        return context

    def get_success_url(self):
        return reverse('dashboard:course-update', args=[self.get_object().pk])

    def form_valid(self, form):
        form.save(teacher = self.request.user)
        return self.render_to_response(self.get_context_data(form=form))

    def get_queryset(self):
        if not self.request.user.is_authenticated:
            return Course.objects.none()
        return Course.objects.filter(teacher = self.request.user)


class CourseDeleteView(DeleteView):
    success_url = reverse_lazy('dashboard:my-courses')

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return redirect(reverse('user:login') + '?next=' + reverse('dashboard:my-courses'))
        elif not request.user.is_mentor and not request.user.is_superuser:
            return redirect('dashboard:profile')
        return super().dispatch(request, *args, **kwargs)

    def get_queryset(self):
        return Course.objects.filter(teacher = self.request.user)


class MyCourseView(ListView):
    template_name = 'dashboard/my-courses.html'
    paginate_by = 9

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return redirect(reverse('user:login') + '?next=' + reverse('dashboard:my-courses'))
        elif not request.user.is_mentor and not request.user.is_superuser:
            return redirect('dashboard:profile')
        return super().dispatch(request, *args, **kwargs)

    def get_queryset(self):
        return Course.objects.filter(teacher = self.request.user, is_active = True).prefetch_related('seasions', 'related_course').annotate(lessons_count = Count('seasions__lessons')).order_by('name')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['current_page'] = 'my-courses'
        context['current_url'] = self.request.get_full_path()
        context['active_tab'] = 'published'
        context['active_courses'] = Course.objects.filter(teacher = self.request.user, is_active = True).count()
        context['inactive_courses'] = Course.objects.filter(teacher = self.request.user, is_active = False).count()
        context['all_bookmarks'] = [course.media_id for course in Bookmark.objects.filter(user = self.request.user)]

        cart, total_price, cart_courses = get_cart(self.request.user)
        context['cart_courses'] = cart_courses
        context['total_price'] = total_price
        return context


class MyCourseNotPublishedView(ListView):
    template_name = 'dashboard/my-courses.html'
    paginate_by = 9

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return redirect(reverse('user:login') + '?next=' + reverse('dashboard:my-courses-not-published'))
        elif not request.user.is_mentor and not request.user.is_superuser:
            return redirect('dashboard:profile')
        return super().dispatch(request, *args, **kwargs)

    def get_queryset(self):
        return Course.objects.filter(teacher = self.request.user, is_active = False).prefetch_related('seasions', 'related_course').annotate(lessons_count = Count('seasions__lessons')).order_by('name')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['current_page'] = 'my-courses'
        context['current_url'] = self.request.get_full_path()
        context['active_tab'] = 'not-published'
        context['active_courses'] = Course.objects.filter(teacher = self.request.user, is_active = True).count()
        context['inactive_courses'] = Course.objects.filter(teacher = self.request.user, is_active = False).count()

        cart, total_price, cart_courses = get_cart(self.request.user)
        context['cart_courses'] = cart_courses
        context['total_price'] = total_price
        return context


class MyBookmarkListView(LoginRequiredMixin, ListView):
    template_name = 'dashboard/my-bookmark.html'
    paginate_by = 9

    def get_queryset(self):
        return Bookmark.objects.filter(user = self.request.user)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['current_page'] = 'my_bookmarked_courses'

        cart, total_price, cart_courses = get_cart(self.request.user)
        context['cart_courses'] = cart_courses
        context['total_price'] = total_price
        return context

templates/dashboard/change-password.html
{% extends 'dashboard/base.html' %}
{% block title %}تغییر پسورد | آکادمی من {% endblock %}
{% block content %}
                    <div class="col-lg-9">
                        <div class="tpd-course-area">
                            <div class="tp-dashboard-tab mb-60">
                                <h2 class="tp-dashboard-tab-title">تنظیمات</h2>
                                <div class="tp-dashboard-tab-list">
                                    <ul>
                                        <li><a href="{% url 'dashboard:profile' %}">مشخصات</a></li>
                                        <li><a class="active" href="{% url 'dashboard:change-password' %}">رمز عبور</a></li>
                                        <li><a href="instructor-setting-withdraw.html">برداشت</a></li>
                                        <li><a href="instructor-setting-social.html">نمایه اجتماعی</a></li>
                                    </ul>
                                </div>
                            </div>
                            <div class="tpd-setting-box">
                                {% if messages %}
                                {% for message in messages %}
                                <div class="alert alert-warning">{{ message }}</div>
                                {% endfor %}
                                {% endif %}
                                <form method="post" class="tpd-setting-password-content">
                                    {% for error in form.non_field_errors %}
                                    <div class="alert alert-danger">
                                        {{ error }}
                                    </div>
                                    {% endfor %}

                                    {% csrf_token %}
                                    {% for field in form %}
                                    <div class="col-lg-8">
                                        <div class="tpd-input">
                                            <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                                            {{ field }}
                                            {{ field.help_text }}
                                        </div>
                                    </div>
                                    {% endfor %}
                                    <div class="col-lg-8">
                                        <div class="tpd-setting-btn">
                                            <button>رمز عبور جدید را تنظیم کنید</button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
{% endblock %}

templates/dashboard/my-bookmark.html
{% extends 'dashboard/base.html' %}
{% load static %}
{% block title %}دوره های پسندیده | آکادمی من{% endblock %}
{% block content %}
                    <div class="col">
                        <div class="tpd-content-layout">
                            <div class="course-area">
                                <div class="row">
                                    <div class="col-lg-6">
                                        <div class="tp-dashboard-section">
                                            <h2 class="tp-dashboard-title">لیست خواسته</h2>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    {% for course in object_list %}
                                    <div class="col-xl-4 col-sm-6">
                                        <div class="tp-dashboard-course tp-dashboard-course-2 mb-25">
                                            <div class="tp-course-teacher mb-15">
                                                <span>
                                                    <img alt="" src="{% if course.get_object.teacher.profile.picture %}{{ course.get_object.teacher.profile.picture.url }}{% else %}{% static 'img/event/user.jpg' %}{% endif %}">{{ course.get_object.teacher.get_full_name|default:course.get_object.teacher.username }}
                                                </span>
                                            </div>
                                            <div class="tp-dashboard-course-thumb">
                                                <a href="#">
                                                    <img alt="" src="{{ course.get_object.thumbnail.url }}">
                                                </a>
                                            </div>
                                            <div class="tp-dashboard-course-content">
                                                <div class="tp-dashboard-rating">
                                                    <i class="fa-solid fa-star"></i>
                                                    <i class="fa-solid fa-star"></i>
                                                    <i class="fa-solid fa-star"></i>
                                                    <i class="fa-solid fa-star"></i>
                                                    <i class="fa-solid fa-star"></i>
                                                    <span>(15 بررسی)</span>
                                                </div>
                                                <h4 class="tp-dashboard-course-title"><a href="#">{{ course.get_object.name }}</a></h4>
                                                <div class="tp-dashboard-course-meta">
                                                    <span>
                                                        <span>
                                                            <svg fill="none" height="14" viewbox="0 0 15 14" width="15" xmlns="http://www.w3.org/2000/svg">
                                                                <path
                                                                    d="M13.9228 10.0426V2.29411C13.9228 1.51825 13.2949 0.953997 12.5252 1.01445H12.4847C11.1276 1.12529 9.07163 1.82055 7.91706 2.53596L7.80567 2.6065C7.62337 2.71733 7.30935 2.71733 7.11692 2.6065L6.9549 2.50573C5.81046 1.79033 3.75452 1.1152 2.3974 1.00437C1.62768 0.943911 0.999756 1.51827 0.999756 2.28405V10.0426C0.999756 10.6573 1.50613 11.2417 2.12393 11.3122L2.30622 11.3425C3.70386 11.5238 5.87126 12.2392 7.10685 12.9143L7.1372 12.9244C7.30937 13.0252 7.59293 13.0252 7.75498 12.9244C8.99057 12.2393 11.1681 11.5339 12.5758 11.3425L12.7885 11.3122C13.4164 11.2417 13.9228 10.6674 13.9228 10.0426Z"
                                                                    stroke="#94928E" stroke-linecap="round"
                                                                    stroke-linejoin="round" stroke-width="1.2"></path>
                                                                <path d="M7.46118 2.81787V12.4506" stroke="#94928E"
                                                                    stroke-linecap="round" stroke-linejoin="round"
                                                                    stroke-width="1.2"></path>
                                                            </svg>
                                                        </span>
                                                        {{ course.get_object.lessons_count }}
                                                    </span>
                                                    <span>
                                                        <span>
                                                            <svg fill="none" height="15" viewbox="0 0 13 15" width="13" xmlns="http://www.w3.org/2000/svg">
                                                                <path
                                                                    d="M6.57134 7.5C8.36239 7.5 9.81432 6.04493 9.81432 4.25C9.81432 2.45507 8.36239 1 6.57134 1C4.7803 1 3.32837 2.45507 3.32837 4.25C3.32837 6.04493 4.7803 7.5 6.57134 7.5Z"
                                                                    stroke="#94928E" stroke-linecap="round"
                                                                    stroke-linejoin="round" stroke-width="1.2"></path>
                                                                <path
                                                                    d="M12.1426 14C12.1426 11.4845 9.64553 9.44995 6.57119 9.44995C3.49684 9.44995 0.999756 11.4845 0.999756 14"
                                                                    stroke="#94928E" stroke-linecap="round"
                                                                    stroke-linejoin="round" stroke-width="1.2"></path>
                                                            </svg>
                                                        </span>
                                                        45 دانش آموز
                                                    </span>
                                                </div>
                                                <div class="tp-dashboard-btn d-flex align-items-center justify-content-between">
                                                    <a class="tpd-btn-border" href="#">
                                                        <span>
                                                            <svg fill="none" height="18" viewbox="0 0 17 18" width="17" xmlns="http://www.w3.org/2000/svg">
                                                                <path
                                                                    d="M5.07918 12.2H10.8141C14.3574 12.2 14.8963 9.94466 15.5499 6.65524C15.7384 5.70647 15.8327 5.23208 15.606 4.91603C15.3793 4.59998 14.9448 4.59998 14.0758 4.59998H3.5"
                                                                    stroke="currentColor" stroke-linecap="round"
                                                                    stroke-width="1.5"></path>
                                                                <path
                                                                    d="M5.08297 12.2L3.01325 2.21194C2.8375 1.49968 2.20585 1 1.48122 1H0.740234"
                                                                    stroke="currentColor" stroke-linecap="round"
                                                                    stroke-width="1.5"></path>
                                                                <path
                                                                    d="M5.77401 12.2H5.44916C4.37267 12.2 3.5 13.121 3.5 14.2571C3.5 14.4465 3.64544 14.6 3.82486 14.6H12.5803"
                                                                    stroke="currentColor" stroke-linecap="round"
                                                                    stroke-linejoin="round" stroke-width="1.5"></path>
                                                                <ellipse cx="7.05938" cy="15.8" rx="1.18438" ry="1.2"
                                                                    stroke="currentColor" stroke-width="1.5"></ellipse>
                                                                <ellipse cx="12.5809" cy="15.8" rx="1.18438" ry="1.2"
                                                                    stroke="currentColor" stroke-width="1.5"></ellipse>
                                                            </svg>
                                                        </span>
                                                        سبد خرید
                                                    </a>
                                                    <div class="tp-dashboard-course-free"><span>رایگان</span></div>
                                                </div>
                                                <div class="tp-dashboard-btn d-flex align-items-center justify-content-between">
                                                    <a onclick="sendFormToURL('{% url 'academy:bookmarker' 'course' course.get_object.id %}?next={{ request.get_full_path }}')"
                                                        class="btn btn-danger my-1" style="width: 100%;">
                                                            <span class="ml-4">
                                                                <i class="fa-solid fa-bookmark-slash"></i>
                                                            </span>
                                                            حذف از ذخیره شده ها
                                                        </a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    {% empty %}
                                        <div style="text-align: center; margin-bottom: 50px;">چیزی برای نمایش وجود نداره</div>
                                    {% endfor %}
                                </div>
                            </div>
                            {% include 'components/pagination.html' with object=page_obj %}
                        </div>
                    </div>
{% endblock %}