academy/urls.py
from django.urls import path
from .views import (Home, CourseFilterView, CourseCategoryView, CourseDetailsView, BookmarkView)


app_name = 'academy'
urlpatterns = [
    path('courses', CourseFilterView.as_view(), name='courseslist'),
    path('category/<slug:category_slug>', CourseCategoryView.as_view(), name='category'),
    path('bookmark/<str:content_type>/<int:course_id>/', BookmarkView.as_view(), name='bookmarker'),
    path('courses/<int:course_id>', CourseDetailsView.as_view(), name='course-details'),
    path('', Home.as_view(), name = 'home'),
]

cart/urls.py
from django.urls import path
from .views import AddCourseToCartView, CheckoutView, RevmoveCourseFromCartView, PaymentView

app_name = 'cart'
urlpatterns = [
    path('add/<str:content_type>/<int:course_id>/', AddCourseToCartView.as_view(), name='cart-add'),
    path('remove/<str:content_type>/<int:course_id>/', RevmoveCourseFromCartView.as_view(), name='cart-remove'),
    path('checkout/', CheckoutView.as_view(), name='cart-checkout'),
    path('payment/', PaymentView.as_view(), name='payment'),
]

dashboard/urls.py
from django.urls import path
from .views import (ProfileView, ChangePasswordView, CourseAddView, CourseUpdateView, CourseDeleteView, MyCourseView, MyCourseNotPublishedView,
                    MyBookmarkListView)

app_name = 'dashboard'
urlpatterns = [
    path('profile/', ProfileView.as_view(), name = 'profile'),
    path('change-password/', ChangePasswordView.as_view(), name = 'change-password'),
    path('course/add/', CourseAddView.as_view(), name='course-add'),
    path('course/<int:pk>/update/', CourseUpdateView.as_view(), name='course-update'),
    path('course/<int:pk>/delete/', CourseDeleteView.as_view(), name='course-delete'),
    path('my-course/', MyCourseView.as_view(), name='my-courses'),
    path('my-course/pending/', MyCourseNotPublishedView.as_view(), name='my-courses-not-published'),
    path('my-bookmarks/', MyBookmarkListView.as_view(), name='my-bookmark-list'),

]

myacademy/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('academy.urls')),
    path('', include('user.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('cart/', include('cart.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path
from .views import (LoginView, LogoutView, RegisterView, ActivateRegisterdAccountView, ForgotPasswordView, ConfirmForgotPasswordView)


app_name = 'user'
urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout', LogoutView.as_view(), name='logout'),
    path('register/active-account/', ActivateRegisterdAccountView.as_view(), name='active-account'),
    path('forgot-password/', ForgotPasswordView.as_view(), name='forgot-password'),
    path('forgot-password/confirm/', ConfirmForgotPasswordView.as_view(), name='confirm-forgot-password'),
]

user/forms.py
from django import forms
from .models import Profile, User, OTPCode
from django_recaptcha.fields import ReCaptchaField
from django_recaptcha.widgets import ReCaptchaV2Checkbox
from django.core.exceptions import ValidationError
from django.utils import timezone
from datetime import timedelta
from random import randint


class RecaptchaFrom(forms.Form):
    recaptcha = ReCaptchaField(widget=ReCaptchaV2Checkbox)


class RegisterForm(forms.ModelForm):
    password1 = forms.CharField(max_length=100, widget=forms.PasswordInput(attrs={'class': 'password-input p-relative'}), label='پسورد')
    password2 = forms.CharField(max_length=100, widget=forms.PasswordInput(attrs={'class': 'password-input p-relative'}), label='تکرار پسورد')
    accept_rules = forms.BooleanField(widget=forms.CheckboxInput, label='پذیرش قوانین')

    class Meta:
        model = User
        fields = ['username', 'email', 'phone_number']

    def clean_password2(self):
        password1 = self.cleaned_data['password1']
        password2 = self.cleaned_data['password2']
        if password1 != password2:
            raise ValidationError('passwords dont match')
        return password2

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password1'])
        if commit:
            user.save()
        Profile.objects.create(user=user)
        return user

    def send_otp_code_to_number(self):
        code = randint(12121, 98989)
        otp = OTPCode.objects.create(phone_number = self.cleaned_data['phone_number'], expire_time = timedelta(minutes=4) + timezone.now(), code = code, code_type = 'register')
        # add send code statement here
        return True if otp else False


class LoginForm(forms.Form):
    username = forms.CharField(max_length=150, label='نام کاربری')
    password = forms.CharField(max_length=150, widget=forms.PasswordInput, label='پسورد')


class ChangePasswordForgotPasswordFrom(forms.Form):
    password1 = forms.CharField(label='پسورد', widget=forms.PasswordInput(attrs={'placeholder': 'رمز عبور'}))
    password2 = forms.CharField(label='تکرار پسورد', widget=forms.PasswordInput(attrs={'placeholder': 'تکرار رمز عبور'}))
    code = forms.IntegerField(label='کد ارسال شده', widget=forms.NumberInput(attrs={'placeholder': 'کد ارسال شده'}))

    def clean(self):
        cleaned_data = self.cleaned_data
        password1, password2 = cleaned_data.get("password1", None), cleaned_data.get("password2", None)

        if (
            not password1
            or not password2
            or len(password1) < 7
            or password1.isnumeric()
            or password1.isalpha()
        ):
            raise ValidationError("لطفا پسورد قوی با توجه با نکات امنیتی انتخاب کنید.")
        if password1 != password2:
            raise ValidationError('پسورد ها با هم مطابقت ندارند.')
        return cleaned_data

user/views.py
from datetime import timedelta
from random import randint
from django.conf import settings
from django.shortcuts import redirect, render
from django.views import View
from .forms import ChangePasswordForgotPasswordFrom, LoginForm, RecaptchaFrom, RegisterForm
from .models import OTPCode, User
from django.contrib.auth import login, authenticate, logout
from django.utils import timezone
from django.db.models import Q


class RegisterView(View):
    template_name = 'user/register.html'

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('academy:home')
        self.context = {
            'recaptcha': RecaptchaFrom(),
            'register_form': RegisterForm()
        }
        return super().dispatch(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name, self.context)

    def post(self, request, *args, **kwargs):
        recaptcha_form = RecaptchaFrom(request.POST)
        if recaptcha_form.is_valid():
            register_form = RegisterForm(request.POST)
            if register_form.is_valid():
                register_form.save()
                request.session['phone_number'] = register_form.cleaned_data['phone_number']
                request.session.modified = True
                res = register_form.send_otp_code_to_number()
                if not res:
                    self.context['msg'] = 'otp connection failed'
                return redirect('user:active-account')
            else:
                self.context['register_form'] = register_form
                self.context['msg'] = 'register form error'
        else:
            self.context['msg'] = 'captcha error'
        return render(request, self.template_name, self.context)


class LoginView(View):
    template_name = 'user/login.html'

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('academy:home')

        self.context = {
            'login_form': LoginForm(),
            'recaptcha': RecaptchaFrom(),
        }
        return super().dispatch(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name, self.context)

    def post(self, request, *args, **kwargs):
        recaptcha_form = RecaptchaFrom(request.POST)
        if recaptcha_form.is_valid():
            login_form = LoginForm(request.POST)
            if login_form.is_valid():
                user = authenticate(request, **login_form.cleaned_data)
                if user:
                    login(request, user)
                    # TODO: Add login redirect url
                    return redirect(request.GET.get('next', 'dashboard:profile'))
                self.context['msg'] = 'authentication failed'
            self.context['login_form'] = login_form
        else:
            self.context['msg'] = 'captcha error'
        return render(request, self.template_name, self.context)


class LogoutView(View):
    def get(self, request, *args, **kwargs):
        if request.user.is_anonymous:
            return redirect('user:login')
        logout(request)
        return redirect('academy:home')


class ActivateRegisterdAccountView(View):
    template_name = 'user/activate.html'

    def dispatch(self, request, *args, **kwargs):
        self.phone_number = request.session.get('phone_number', None)
        if request.user.is_authenticated:
            return redirect('academy:home')
        elif self.phone_number is None:
            return redirect('user:register')

        self.context = {
            'msg': 'code sended',
            'recaptcha': RecaptchaFrom()
            }
        return super().dispatch(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name, self.context)

    def post(self, request, *args, **kwargs):
        self.context = {
            'recaptcha': RecaptchaFrom()
        }
        recaptcha_form = RecaptchaFrom(request.POST)
        if recaptcha_form.is_valid():
            code = request.POST.get('code', None)
            if code and code.isnumeric():
                otp = OTPCode.objects.filter(code = code, phone_number = self.phone_number, expire_time__gte = timezone.now())
                if otp.exists():
                    user = User.objects.get(phone_number = otp.first().phone_number)
                    user.is_active = True
                    user.save()
                    otp.delete()
                    request.session.pop('phone_number')
                    request.session.modified = True
                    if settings.LOGIN_AFTER_SIGNUP:
                        login(request, user)
                    if settings.REDIRECT_AFTER_LOGIN_AFTER_SIGNUP:
                        return redirect(settings.REDIRECT_AFTER_LOGIN_AFTER_SIGNUP)
                    else:
                        return redirect('academy:home')
                else:
                    self.context['msg'] = 'code failed'
            else:
                self.context['msg'] = 'code must be integer'
        else:
            self.context['msg'] = 'invalid captcha'
        return render(request, self.template_name, self.context)


class ForgotPasswordView(View):
    template_name = 'user/forgot-password.html'

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('academy:home')
        return super().dispatch(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name, {'recaptcha': RecaptchaFrom()})

    def post(self, request, *args, **kwargs):
        recaptcha_form = RecaptchaFrom(request.POST)
        context = {}

        if recaptcha_form.is_valid():
            token = request.POST.get('token', None)
            if token:
                try:
                    user = User.objects.get(Q(username = token) | Q(email = token) | Q(phone_number = token))

                except:
                    context['msg'] =  'user not found'
                else:
                    last_otp = OTPCode.objects.filter(phone_number = user.phone_number, code_type='forgot-password')
                    send_code = False
                    if last_otp.exists():
                        if last_otp.first().expire_time < timezone.now() :
                            last_otp.delete()
                            send_code = True
                        else:
                            context['msg'] = 'please wait'
                    else:
                        send_code = True

                    if send_code:
                        code = randint(12121, 98989)
                        OTPCode.objects.create(code = code, expire_time = timedelta(minutes=5) + timezone.now(), phone_number = user.phone_number, code_type = 'forgot-password')
                        
                        request.session['phone_number'] = user.phone_number
                        request.session.modified = True
                        # try:
                        #     pass
                        #     #send code
                        # except:
                        #     context['msg'] = 'otp failed' # for error when try for send code to Phone number
                        return redirect('user:confirm-forgot-password')
            else:
                context['msg'] = 'token failed'
        else:
            context['msg'] = 'ivalid captcha'
        context['recaptcha'] = recaptcha_form
        return render(request, self.template_name, context)


class ConfirmForgotPasswordView(View):
    template_name = 'user/confirm-forgot-password.html'

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('academy:home')
        self.phone_number = request.session.get('phone_number', None)
        if self.phone_number is None:
            return redirect('academy:home')

        self.context = {
            'recaptcha': RecaptchaFrom(),
            'change_password_form': ChangePasswordForgotPasswordFrom()
        }
        return super().dispatch(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name, self.context)

    def post(self, request, *args, **kwargs):
        recaptcha_form = RecaptchaFrom(request.POST)
        if recaptcha_form.is_valid():
            change_password_form = ChangePasswordForgotPasswordFrom(request.POST)
            if change_password_form.is_valid():
                code = change_password_form.cleaned_data['code']
                otp = OTPCode.objects.filter(Q(code_type = 'forgot-password'), phone_number = self.phone_number)
                otp_with_code  = otp.filter(code = code, expire_time__gte = timezone.now())
                if otp_with_code.exists():
                    user = User.objects.get(phone_number = otp_with_code.first().phone_number)
                    user.set_password(change_password_form.cleaned_data['password1'])
                    user.save()
                    otp.delete()
                    request.session.pop('phone_number')
                    request.session.modified = True
                    # TODO: Redirect to user panel
                    # TODO: if on settings set can auto login after change password and redirect to user panel
                    return redirect(request.GET.get('next', 'user:login'))
                else:
                    self.context['msg'] = 'invalid code'
            self.context['change_password_form'] = change_password_form
        else:
            self.context['msg'] = 'invalid recaptcha'
        return render(request, self.template_name, self.context)

templates/user/activate.html
{% extends 'user/base-auth.html' %}
{% block title %}فعال کردن اکانت | اکادمی من{% endblock %}
{% block content %}
<div class="tp-login-from-heading text-center">
<h4 class="tp-login-from-title">پسورد اکانت خود را بازیابی کنید</h4>
<p>حساب کاربری دارید؟<a href="{% url 'user:login' %}">وارد شوید</a></p>
</div>
<div class="tp-login-input-form">
<form method="post" class="row">
    {% csrf_token %}
    <div class="col-12">
        <div class="tp-login-input p-relative">
            <label>کد تایید</label>
            <input placeholder="کد تایید" name="code" type="number">
        </div>
    </div>
    <div class="col-12">
        {{ recaptcha }}
    </div>
    <div class="col-12">
        <div class="row">
            {% if msg in 'code failed,code must be integer,invalid captcha' %}
            <div class="col-12">
                <div class="alert alert-danger d-flex align-items-center text-start" role="alert">
                    <svg xmlns="http://www.w3.org/2000/svg" style="max-width: 16px;max-height: 14px;" class="bi bi-exclamation-triangle-fill flex-shrink-0 me-2" viewBox="0 0 16 16" role="img" aria-label="Warning:">
                        <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
                    </svg>
                    {% if msg == 'code failed' %}
                    <div>کد تایید اشتباه است یا منقضی شده.</div>
                    {% elif msg == 'code must be integer' %}
                    <div>کد تایید باید عدد باشد.</div>
                    {% elif msg == 'invalid captcha' %}
                    <div>کپچا اشتباه است.</div>
                    {% endif %}
                </div>
            </div>
            {% endif %}

            {% if msg == 'code sended' %}
            <div class="col-12">
                <svg xmlns="http://www.w3.org/2000/svg" class="d-none">
                    <symbol id="check-circle-fill" viewBox="0 0 16 16">
                        <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z"/>
                    </symbol>
                </svg>
                <div class="alert alert-success d-flex align-items-center" role="alert">
                    <svg class="bi flex-shrink-0 me-2" style="max-width: 16px;max-height: 14px;" role="img" aria-label="Success:"><use xlink:href="#check-circle-fill"/></svg>
                    <div>کد با موفقیت ارسال شد.</div>
                </div>
            </div>
            {% endif %}

            <div class="col-6">
                <div class="tp-login-input-remeber text-start"><a href="{% url 'user:login' %}">وارد شوید</a></div>
            </div>
            <div class="col-6">
                <div class="tp-login-input-remeber text-end"><a href="{% url 'user:register' %}">ثبت نام</a></div>
            </div>
        </div>
        <div class="tp-login-from-btn">
            <button class="tp-btn-inner w-100 text-center">فعال کردن حساب</button>
        </div>
        <div class="tp-login-from-autor text-center">
            <p><span>تلفن پشتیبانی:</span>+989123456789</p>
            <p><span>ایمیل پشتیبانی:</span>test@gmail.com</p>
        </div>
    </div>
</form>
{% endblock %}

templates/user/change-password.html
{% extends 'user/base.html' %}
{% block title %}تغییر پسورد | آکادمی من {% endblock %}
{% block content %}
                    <div class="col-lg-9">
                        <div class="tpd-course-area">
                            <div class="tp-dashboard-tab mb-60">
                                <h2 class="tp-dashboard-tab-title">تنظیمات</h2>
                                <div class="tp-dashboard-tab-list">
                                    <ul>
                                        <li><a href="{% url 'user:profile' %}">مشخصات</a></li>
                                        <li><a class="active" href="{% url 'user:change-password' %}">رمز عبور</a></li>
                                        <li><a href="instructor-setting-withdraw.html">برداشت</a></li>
                                        <li><a href="instructor-setting-social.html">نمایه اجتماعی</a></li>
                                    </ul>
                                </div>
                            </div>
                            <div class="tpd-setting-box">
                                {% if messages %}
                                {% for message in messages %}
                                <div class="alert alert-warning">{{ message }}</div>
                                {% endfor %}
                                {% endif %}
                                <form method="post" class="tpd-setting-password-content">
                                    {% for error in form.non_field_errors %}
                                    <div class="alert alert-danger">
                                        {{ error }}
                                    </div>
                                    {% endfor %}

                                    {% csrf_token %}
                                    {% for field in form %}
                                    <div class="col-lg-8">
                                        <div class="tpd-input">
                                            <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                                            {{ field }}
                                            {{ field.help_text }}
                                        </div>
                                    </div>
                                    {% endfor %}
                                    <div class="col-lg-8">
                                        <div class="tpd-setting-btn">
                                            <button>رمز عبور جدید را تنظیم کنید</button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
{% endblock %}

templates/user/profile.html
{% extends 'user/base.html' %}
{% load static %}
{% block title %}پروفایل | آکادمی من{% endblock %}
{% block content %}
<script src="{% static 'js/vendor/jquery.js' %}"></script>

<div class="row">
    <div class="col-12">
        <div class="tp-dashboard-tab mb-25">
            <h2 class="tp-dashboard-tab-title">تنظیمات</h2>
            <div class="tp-dashboard-tab-list">
                <ul>
                    <li><a class="active" href="{% url 'user:profile' %}">مشخصات</a>
                    </li>
                    <li><a href="{% url 'user:change-password' %}">رمز عبور</a></li>
                    <li><a href="instructor-setting-withdraw.html">برداشت</a></li>
                    <li><a href="instructor-setting-social.html">نمایه اجتماعی</a></li>
                </ul>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-12">
        <form method="post" enctype="multipart/form-data" class="tpd-setting-box profile">
            {% csrf_token %}
            <div class="tp-dashboard-banner-bg profile mb-100"
                data-background="{% static 'img/dashboard/bg/dashboard-bg-1.jpg' %}">
                <div class="tp-instructor-wrap d-flex justify-content-between">
                    <div class="tp-instructor-info d-flex">
                        <div class="tp-instructor-avatar p-relative profile">
                            <img alt="" src="{% if user.profile.picture %}{{ user.profile.picture.url }}{% else %}{% static 'img/event/user.jpg' %}{% endif %}">
                            <span>
                                <svg fill="none" height="38" viewbox="0 0 38 38" width="38" xmlns="http://www.w3.org/2000/svg">
                                    <circle cx="19" cy="19" fill="white" r="18" stroke="#E6E8F0"></circle>
                                    <path
                                        d="M23.352 13.5172L23.272 13.3463C23.056 12.9034 22.808 12.3907 22.656 12.0954C22.288 11.3962 21.656 11.0078 20.88 11H17.112C16.336 11.0078 15.712 11.3962 15.344 12.0954C15.184 12.4062 14.912 12.9656 14.688 13.424L14.64 13.5172C14.616 13.5794 14.552 13.6104 14.488 13.6104C12.56 13.6104 11 15.1332 11 16.9978V21.6127C11 23.4772 12.56 25 14.488 25H23.512C25.432 25 27 23.4772 27 21.6127V16.9978C27 15.1332 25.432 13.6104 23.512 13.6104C23.44 13.6104 23.384 13.5716 23.352 13.5172Z"
                                        fill="#303651"></path>
                                    <path
                                        d="M19.0035 15.9806C19.8435 15.9806 20.6355 16.2992 21.2275 16.8741C21.8195 17.4568 22.1475 18.2259 22.1475 19.0339C22.1395 19.8808 21.7875 20.6421 21.2195 21.1937C20.6515 21.7454 19.8675 22.0872 19.0035 22.0872C18.1635 22.0872 17.3795 21.7687 16.7795 21.1937C16.1875 20.6111 15.8595 19.8497 15.8595 19.0339C15.8515 18.2259 16.1795 17.4646 16.7715 16.8819C17.3715 16.2992 18.1635 15.9806 19.0035 15.9806ZM19.0035 17.146C18.4835 17.146 17.9955 17.3402 17.6195 17.7054C17.2515 18.0628 17.0515 18.5367 17.0595 19.0262V19.0339C17.0595 19.5389 17.2595 20.0128 17.6275 20.3702C17.9955 20.7276 18.4835 20.9218 19.0035 20.9218C20.0755 20.9218 20.9395 20.075 20.9475 19.0339C20.9475 18.5289 20.7475 18.055 20.3795 17.6976C20.0115 17.3402 19.5235 17.146 19.0035 17.146ZM23.4915 15.7942C23.8915 15.7942 24.2195 16.1127 24.2195 16.5012C24.2195 16.8896 23.8915 17.2004 23.4915 17.2004C23.0915 17.2004 22.7715 16.8896 22.7715 16.5012C22.7715 16.1127 23.0915 15.7942 23.4915 15.7942Z"
                                        fill="white"></path>
                                </svg>
                            </span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="tpd-setting-from">
                {% if messages %}
                {% for message in messages %}
                <div class="alert alert-success">
                    {{ message }}
                </div>
                {% endfor %}
                {% endif %}
                <div class="row"> 
                    <div class="col-lg-6">
                        <div class="tpd-input">
                            <label for="{{ form.first_name.id_for_label }}">{{ form.first_name.label }}</label>
                            {{ form.first_name }}
                        </div>
                        {% for error in form.first_name.errors %}
                        <div class="alert alert-danger" role="alert">
                            {{ error }}
                        </div>
                        {% endfor %}
                    </div>
                    <div class="col-lg-6">
                        <div class="tpd-input">
                            <label for="{{ form.last_name.id_for_label }}">{{ form.last_name.label }}</label>
                            {{ form.last_name }}
                        </div>
                        {% for error in form.last_name.errors %}
                        <div class="alert alert-danger" role="alert">
                            {{ error }}
                        </div>
                        {% endfor %}
                    </div>
                    <div class="col-lg-6">
                        <div class="tpd-input">
                            <label for="{{ form.username.id_for_label }}">{{ form.username.label }}</label>
                            {{ form.username }}
                        </div>
                        {% for error in form.username.errors %}
                        <div class="alert alert-danger" role="alert">
                            {{ error }}
                        </div>
                        {% endfor %}
                    </div>
                    <div class="col-lg-12">
                        <div class="tpd-input">
                            <label class="d-block" for="{{ form.aboute.id_for_label }}">{{ form.aboute.label }}</label>
                            {{ form.aboute }}
                        </div>
                        {% for error in form.aboute.errors %}
                        <div class="alert alert-danger" role="alert">
                            {{ error }}
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
            <div class="tpd-setting-cartificate">
                <h5 class="tpd-setting-cartificate-title">عکس پروفایل</h5>
                <div class="tpd-setting-cartificate-upload d-flex align-items-center">
                    <div class="tpd-setting-cartificate-content">
                        <!-- <p>اندازه: 700x430 پیکسل</p><span class="upload-btn"> -->
                            {{ form.picture }}
                            <!-- <input accept="image/png, image/jpeg" id="tpd-setting-cartificate-input" type="file"> -->
                            {% for error in form.aboute.errors %}
                            <div class="alert alert-danger" role="alert">
                                {{ error }}
                            </div>
                            {% endfor %}
                        </span>
                    </div>
                </div>
                <!-- <div class="tpd-setting-cartificate-btn"><button>ذخیره تغییرات</button>
                </div> -->
                <button type="button" style="display: none;" id="edit-profile" class="btn btn-info m-1 shadow border border-2 border-primary">ویرایش </button>
                <button type="submit" id="submit-edit-profile" class="btn btn-success m-1 shadow border border-2 border-info">ذخیره</button>
                <button type="reset" style="display: none;" id="reset-edit-profile" class="btn btn-danger m-1 shadow border border-2 border-warning">بازگشت</button>
                <script>
                    // If Jquery loaded submit and reset btns hided and edit btn showed
                    // else only submit btn showed

                    $(document).ready(function(){
                        $(".input").each(function () {
                            $(this).prop("disabled", true)
                        })
                        $("#edit-profile").toggle();
                        $("#submit-edit-profile").toggle()
                        $("#edit-profile").click(function() {
                            $(this).toggle();
                            $('#submit-edit-profile').toggle()
                            $('#reset-edit-profile').toggle()
                            $(".input").each(function () {
                                $(this).prop("disabled", !$(this).prop("disabled"));
                            });
                        });
                        $("#reset-edit-profile").click(function() {
                            $(this).toggle();
                            $('#submit-edit-profile').toggle()
                            $('#edit-profile').toggle()
                            $(".input").each(function () {
                                $(this).prop("disabled", !$(this).prop("disabled"));
                            });
                        });
                    });
                </script>
            </div>
        </form>
    </div>
</div>
{% endblock %}